import type { Category, MenuItem, Ingredient, Supplier, Customer, User } from '@/types';

export const SEED_USERS: User[] = [
  { id: 'u1', name: 'Almaz', role: 'owner', pin: '1234' },
  { id: 'u2', name: 'Biruk', role: 'manager', pin: '2345' },
  { id: 'u3', name: 'Chaltu', role: 'cashier', pin: '3456' },
];

export const SEED_CATEGORIES: Category[] = [
  { id: 'cat1', nameEn: 'Main Dishes', nameAm: 'ዋና ምግብ', sortOrder: 1 },
  { id: 'cat2', nameEn: 'Soups & Stews', nameAm: 'ሾርባ እና ወጥ', sortOrder: 2 },
  { id: 'cat3', nameEn: 'Beverages', nameAm: 'መጠጦች', sortOrder: 3 },
  { id: 'cat4', nameEn: 'Juices', nameAm: 'ጭማቂዎች', sortOrder: 4 },
  { id: 'cat5', nameEn: 'Breakfast', nameAm: 'ቁርስ', sortOrder: 5 },
  { id: 'cat6', nameEn: 'Snacks', nameAm: 'መክሰስ', sortOrder: 6 },
];

export const SEED_INGREDIENTS: Ingredient[] = [
  { id: 'ing1', nameEn: 'Teff Flour', nameAm: 'ጤፍ ዱቄት', unit: 'kg', stock: 25, minStock: 5, costPerUnit: 120 },
  { id: 'ing2', nameEn: 'Berbere Spice', nameAm: 'በርበሬ', unit: 'kg', stock: 8, minStock: 2, costPerUnit: 350 },
  { id: 'ing3', nameEn: 'Niter Kibbeh (Butter)', nameAm: 'ንጥር ቅቤ', unit: 'kg', stock: 6, minStock: 2, costPerUnit: 450 },
  { id: 'ing4', nameEn: 'Chicken', nameAm: 'ዶሮ', unit: 'kg', stock: 12, minStock: 3, costPerUnit: 280 },
  { id: 'ing5', nameEn: 'Onions', nameAm: 'ሽንኩርት', unit: 'kg', stock: 20, minStock: 5, costPerUnit: 45 },
  { id: 'ing6', nameEn: 'Garlic', nameAm: 'ነጭ ሽንኩርት', unit: 'kg', stock: 5, minStock: 1, costPerUnit: 200 },
  { id: 'ing7', nameEn: 'Tomatoes', nameAm: 'ቲማቲም', unit: 'kg', stock: 15, minStock: 3, costPerUnit: 60 },
  { id: 'ing8', nameEn: 'Coffee Beans', nameAm: 'ቡና ፍሬ', unit: 'kg', stock: 10, minStock: 2, costPerUnit: 600 },
  { id: 'ing9', nameEn: 'Milk', nameAm: 'ወተት', unit: 'L', stock: 20, minStock: 5, costPerUnit: 80 },
  { id: 'ing10', nameEn: 'Sugar', nameAm: 'ስኳር', unit: 'kg', stock: 30, minStock: 5, costPerUnit: 55 },
  { id: 'ing11', nameEn: 'Shiro Powder', nameAm: 'ሽሮ ዱቄት', unit: 'kg', stock: 10, minStock: 2, costPerUnit: 180 },
  { id: 'ing12', nameEn: 'Lentils', nameAm: 'ምስር', unit: 'kg', stock: 15, minStock: 3, costPerUnit: 100 },
  { id: 'ing13', nameEn: 'Oil', nameAm: 'ዘይት', unit: 'L', stock: 18, minStock: 4, costPerUnit: 130 },
  { id: 'ing14', nameEn: 'Eggs', nameAm: 'እንቁላል', unit: 'pcs', stock: 60, minStock: 12, costPerUnit: 15 },
  { id: 'ing15', nameEn: 'Injera (pieces)', nameAm: 'እንጀራ', unit: 'pcs', stock: 100, minStock: 20, costPerUnit: 12 },
  { id: 'ing16', nameEn: 'Fava Beans', nameAm: 'ባቄላ', unit: 'kg', stock: 12, minStock: 3, costPerUnit: 90 },
  { id: 'ing17', nameEn: 'Mangoes', nameAm: 'ማንጎ', unit: 'kg', stock: 8, minStock: 2, costPerUnit: 150 },
  { id: 'ing18', nameEn: 'Avocados', nameAm: 'አቮካዶ', unit: 'pcs', stock: 30, minStock: 6, costPerUnit: 25 },
  { id: 'ing19', nameEn: 'Limes', nameAm: 'ሎሚ', unit: 'kg', stock: 5, minStock: 1, costPerUnit: 80 },
  { id: 'ing20', nameEn: 'Bananas', nameAm: 'ሙዝ', unit: 'kg', stock: 10, minStock: 2, costPerUnit: 70 },
  { id: 'ing21', nameEn: 'Pasta', nameAm: 'ፓስታ', unit: 'kg', stock: 15, minStock: 4, costPerUnit: 90 },
  { id: 'ing22', nameEn: 'Minced Beef', nameAm: 'የተፈጨ ሥጋ', unit: 'kg', stock: 10, minStock: 3, costPerUnit: 450 },
  { id: 'ing23', nameEn: 'Rice', nameAm: 'ሩዝ', unit: 'kg', stock: 20, minStock: 5, costPerUnit: 85 },
  { id: 'ing24', nameEn: 'Tea Leaves', nameAm: 'ሻይ ቅጠል', unit: 'kg', stock: 3, minStock: 1, costPerUnit: 400 },
  { id: 'ing25', nameEn: 'Ginger', nameAm: 'ዝንጅብል', unit: 'kg', stock: 4, minStock: 1, costPerUnit: 150 },
];

export const SEED_MENU_ITEMS: MenuItem[] = [
  {
    id: 'item1', categoryId: 'cat1', nameEn: 'Doro Wat', nameAm: 'ዶሮ ወጥ',
    price: 350, active: true,
    recipe: [{ ingredientId: 'ing4', quantity: 0.3 }, { ingredientId: 'ing5', quantity: 0.15 }, { ingredientId: 'ing2', quantity: 0.05 }, { ingredientId: 'ing3', quantity: 0.05 }, { ingredientId: 'ing14', quantity: 2 }, { ingredientId: 'ing15', quantity: 3 }],
  },
  {
    id: 'item2', categoryId: 'cat1', nameEn: 'Kitfo', nameAm: 'ክትፎ',
    price: 250, active: true,
    recipe: [{ ingredientId: 'ing22', quantity: 0.25 }, { ingredientId: 'ing3', quantity: 0.04 }, { ingredientId: 'ing2', quantity: 0.03 }, { ingredientId: 'ing15', quantity: 2 }],
  },
  {
    id: 'item3', categoryId: 'cat1', nameEn: 'Tibs', nameAm: 'ጥብስ',
    price: 280, active: true,
    recipe: [{ ingredientId: 'ing22', quantity: 0.25 }, { ingredientId: 'ing5', quantity: 0.1 }, { ingredientId: 'ing7', quantity: 0.1 }, { ingredientId: 'ing13', quantity: 0.03 }, { ingredientId: 'ing15', quantity: 2 }],
  },
  {
    id: 'item4', categoryId: 'cat2', nameEn: 'Shiro Tegabeno', nameAm: 'ሽሮ ተጋቤኖ',
    price: 120, active: true,
    recipe: [{ ingredientId: 'ing11', quantity: 0.1 }, { ingredientId: 'ing5', quantity: 0.08 }, { ingredientId: 'ing13', quantity: 0.03 }, { ingredientId: 'ing15', quantity: 2 }],
  },
  {
    id: 'item5', categoryId: 'cat2', nameEn: 'Misir Wat', nameAm: 'ምስር ወጥ',
    price: 100, active: true,
    recipe: [{ ingredientId: 'ing12', quantity: 0.15 }, { ingredientId: 'ing5', quantity: 0.08 }, { ingredientId: 'ing2', quantity: 0.03 }, { ingredientId: 'ing13', quantity: 0.02 }, { ingredientId: 'ing15', quantity: 2 }],
  },
  {
    id: 'item6', categoryId: 'cat3', nameEn: 'Ethiopian Coffee', nameAm: 'ቡና',
    price: 25, active: true,
    recipe: [{ ingredientId: 'ing8', quantity: 0.02 }, { ingredientId: 'ing10', quantity: 0.02 }],
  },
  {
    id: 'item7', categoryId: 'cat3', nameEn: 'Macchiato', nameAm: 'ማኪያቶ',
    price: 35, active: true,
    recipe: [{ ingredientId: 'ing8', quantity: 0.015 }, { ingredientId: 'ing9', quantity: 0.1 }, { ingredientId: 'ing10', quantity: 0.015 }],
  },
  {
    id: 'item8', categoryId: 'cat3', nameEn: 'Tea (Shai)', nameAm: 'ሻይ',
    price: 15, active: true,
    recipe: [{ ingredientId: 'ing24', quantity: 0.005 }, { ingredientId: 'ing10', quantity: 0.015 }, { ingredientId: 'ing25', quantity: 0.005 }],
  },
  {
    id: 'item9', categoryId: 'cat4', nameEn: 'Mango Juice (Spris)', nameAm: 'የማንጎ ጭማቂ',
    price: 50, active: true,
    recipe: [{ ingredientId: 'ing17', quantity: 0.3 }, { ingredientId: 'ing10', quantity: 0.02 }],
  },
  {
    id: 'item10', categoryId: 'cat4', nameEn: 'Avocado Smoothie', nameAm: 'አቮካዶ ስሙዚ',
    price: 55, active: true,
    recipe: [{ ingredientId: 'ing18', quantity: 2 }, { ingredientId: 'ing9', quantity: 0.2 }, { ingredientId: 'ing10', quantity: 0.02 }],
  },
  {
    id: 'item11', categoryId: 'cat5', nameEn: 'Special Ful', nameAm: 'ፉል ልዩ',
    price: 80, active: true,
    recipe: [{ ingredientId: 'ing16', quantity: 0.2 }, { ingredientId: 'ing5', quantity: 0.05 }, { ingredientId: 'ing7', quantity: 0.05 }, { ingredientId: 'ing13', quantity: 0.02 }, { ingredientId: 'ing15', quantity: 2 }],
  },
  {
    id: 'item12', categoryId: 'cat5', nameEn: 'Chechebsa', nameAm: 'ጨጨብሳ',
    price: 90, active: true,
    recipe: [{ ingredientId: 'ing1', quantity: 0.1 }, { ingredientId: 'ing3', quantity: 0.03 }, { ingredientId: 'ing2', quantity: 0.02 }, { ingredientId: 'ing10', quantity: 0.01 }],
  },
  {
    id: 'item13', categoryId: 'cat6', nameEn: 'Sambusa', nameAm: 'ሳምቡሳ',
    price: 30, active: true,
    recipe: [{ ingredientId: 'ing1', quantity: 0.05 }, { ingredientId: 'ing12', quantity: 0.05 }, { ingredientId: 'ing5', quantity: 0.03 }, { ingredientId: 'ing13', quantity: 0.02 }],
  },
  {
    id: 'item14', categoryId: 'cat6', nameEn: 'Kolo (Roasted Barley)', nameAm: 'ኮሎ',
    price: 25, active: true,
    recipe: [{ ingredientId: 'ing23', quantity: 0.05 }],
  },
  {
    id: 'item15', categoryId: 'cat1', nameEn: 'Pasta with Meat Sauce', nameAm: 'ፓስታ ከሥጋ ሶስ',
    price: 180, active: true,
    recipe: [{ ingredientId: 'ing21', quantity: 0.2 }, { ingredientId: 'ing22', quantity: 0.15 }, { ingredientId: 'ing7', quantity: 0.1 }, { ingredientId: 'ing5', quantity: 0.05 }],
  },
];

export const SEED_SUPPLIERS: Supplier[] = [
  { id: 'sup1', name: 'Merkato Wholesale', phone: '+251-911-123456', items: ['Teff Flour', 'Berbere', 'Oil'] },
  { id: 'sup2', name: 'Shola Coffee Export', phone: '+251-922-654321', items: ['Coffee Beans', 'Tea Leaves'] },
  { id: 'sup3', name: 'Piassa Fresh Produce', phone: '+251-933-789012', items: ['Tomatoes', 'Onions', 'Garlic', 'Mangoes'] },
  { id: 'sup4', name: 'Bole Dairy', phone: '+251-944-345678', items: ['Milk', 'Eggs', 'Niter Kibbeh'] },
];

export const SEED_CUSTOMERS: Customer[] = [
  { id: 'c1', name: 'Hailemariam Desalegn', phone: '+251-911-111111', balance: 1250, createdAt: '2025-01-15T08:00:00Z' },
  { id: 'c2', name: 'Mekdes Wondimu', phone: '+251-922-222222', balance: 450, createdAt: '2025-02-01T09:00:00Z' },
  { id: 'c3', name: 'Tadesse Alemu', phone: '+251-933-333333', balance: 0, createdAt: '2025-03-10T10:00:00Z' },
  { id: 'c4', name: 'Birtukan Lemma', phone: '+251-944-444444', balance: 780, createdAt: '2025-01-20T11:00:00Z' },
  { id: 'c5', name: 'Dawit Eshete', phone: '+251-955-555555', balance: 0, createdAt: '2025-04-05T12:00:00Z' },
];

export const SEED_CUSTOMER_LEDGER: { customerId: string; entries: { type: 'charge' | 'payment'; amount: number; description: string; createdAt: string }[] }[] = [
  {
    customerId: 'c1', entries: [
      { type: 'charge', amount: 350, description: 'Doro Wat + Coffee', createdAt: '2025-04-01T12:30:00Z' },
      { type: 'charge', amount: 250, description: 'Kitfo + Spris', createdAt: '2025-04-03T13:00:00Z' },
      { type: 'charge', amount: 650, description: 'Catering - 5x Tibs', createdAt: '2025-04-05T14:00:00Z' },
      { type: 'payment', amount: 500, description: 'Tab payment', createdAt: '2025-04-06T10:00:00Z' },
    ],
  },
  {
    customerId: 'c2', entries: [
      { type: 'charge', amount: 120, description: 'Shiro + Injera', createdAt: '2025-04-02T11:00:00Z' },
      { type: 'charge', amount: 330, description: 'Tibs + Macchiato', createdAt: '2025-04-04T12:00:00Z' },
    ],
  },
  {
    customerId: 'c4', entries: [
      { type: 'charge', amount: 480, description: 'Doro Wat x2 + Coffee', createdAt: '2025-04-01T18:00:00Z' },
      { type: 'charge', amount: 300, description: 'Special Ful + Avocado', createdAt: '2025-04-03T08:30:00Z' },
      { type: 'payment', amount: 200, description: 'Partial payment', createdAt: '2025-04-04T09:00:00Z' },
    ],
  },
];

export type Language = 'en' | 'am';

export interface Translations {
  [key: string]: string;
}

export const TRANSLATIONS: Record<Language, Translations> = {
  en: {
    dashboard: 'Dashboard',
    pos: 'Point of Sale',
    inventory: 'Inventory',
    customers: 'Customers',
    reports: 'Reports',
    settings: 'Settings',
    dailyClosing: 'Daily Closing',
    role: 'Role',
    total: 'Total',
    subtotal: 'Subtotal',
    tax: 'VAT (15%)',
    payment: 'Payment',
    cash: 'Cash',
    credit: 'Credit (Wollo)',
    telebirr: 'Telebirr',
    cbeBirr: 'CBE Birr',
    catering: 'Catering',
    transactionId: 'Transaction ID',
    search: 'Search',
    print: 'Print',
    save: 'Save',
    cancel: 'Cancel',
    close: 'Close',
    confirm: 'Confirm',
    todaySales: 'Today Sales',
    lowStock: 'Low Stock',
    foodCost: 'Food Cost %',
    receipt: 'Receipt',
    customer: 'Customer',
    addCustomer: 'Add Customer',
    balance: 'Balance',
    paymentHistory: 'Payment History',
    statement: 'Statement',
    recordPayment: 'Record Payment',
    ingredients: 'Ingredients',
    recipes: 'Recipes',
    purchases: 'Purchases',
    suppliers: 'Suppliers',
    stockIn: 'Stock In',
    stockOut: 'Stock Out',
    reorderLevel: 'Reorder Level',
    unitCost: 'Unit Cost',
    quantity: 'Quantity',
    price: 'Price',
    date: 'Date',
    time: 'Time',
    cashier: 'Cashier',
    manager: 'Manager',
    owner: 'Owner',
    online: 'Online',
    offline: 'Offline',
    syncing: 'Syncing...',
    language: 'Language',
    theme: 'Theme',
    darkMode: 'Dark Mode',
    lightMode: 'Light Mode',
    logout: 'Logout',
    noItems: 'No items',
    addItem: 'Add Item',
    removeItem: 'Remove Item',
    tapToPay: 'Tap to Pay',
    change: 'Change',
    items: 'Items',
    category: 'Category',
    allCategories: 'All',
    vat: 'VAT',
    notes: 'Notes',
    expenses: 'Expenses',
    totalSales: 'Total Sales',
    openingBalance: 'Opening Balance',
    closingBalance: 'Closing Balance',
    cashInDrawer: 'Cash in Drawer',
    difference: 'Difference',
    lowStockItems: 'Low Stock Items',
    completedBy: 'Completed By',
    printSummary: 'Print Summary',
    closeRegister: 'Close Register',
    ethiopianDate: 'Ethiopian Date',
    gregorianDate: 'Gregorian Date',
    menuItem: 'Menu Item',
    saleComplete: 'Sale Complete!',
    processing: 'Processing...',
    noSalesToday: 'No sales today',
    paymentMethod: 'Payment Method',
    itemName: 'Item Name',
    unitPrice: 'Unit Price',
    lineTotal: 'Total',
    customerName: 'Customer Name',
    phone: 'Phone',
    enterTransactionId: 'Enter Transaction ID',
    cashPayment: 'Cash Payment',
    digitalPayment: 'Digital Payment',
    creditPayment: 'Credit (Wollo)',
    eventCatering: 'Event / Catering',
    etb: 'ETB',
  },
  am: {
    dashboard: 'ዳሽቦርድ',
    pos: 'ሽያጭ',
    inventory: 'ክምችት',
    customers: 'ደንበኞች',
    reports: 'ሪፖርቶች',
    settings: 'ቅንብሮች',
    dailyClosing: 'የቀን መዝጊያ',
    role: 'ሚና',
    total: 'ጠቅላላ',
    subtotal: 'ንዑስ ድምር',
    tax: 'ቫት (15%)',
    payment: 'ክፍያ',
    cash: 'ጥሬ ገንዘብ',
    credit: 'ብድር (ዎሎ)',
    telebirr: 'ተለብር',
    cbeBirr: 'ሲቢኢ ብር',
    catering: 'ዝግጅት',
    transactionId: 'የግብይት መለያ',
    search: 'ፈልግ',
    print: 'አትም',
    save: 'አስቀምጥ',
    cancel: 'ሰርዝ',
    close: 'ዝጋ',
    confirm: 'አረጋግጥ',
    todaySales: 'የዛሬ ሽያጭ',
    lowStock: 'ዝቅተኛ ክምችት',
    foodCost: 'የምግብ ዋጋ %',
    receipt: 'ደረሰኝ',
    customer: 'ደንበኛ',
    addCustomer: 'ደንበኛ አክል',
    balance: 'ሂሳብ',
    paymentHistory: 'የክፍያ ታሪክ',
    statement: 'ሂሳብ መግለጫ',
    recordPayment: 'ክፍያ መዝግብ',
    ingredients: 'ንጥረ ነገሮች',
    recipes: 'የምግብ አዘገጃጀት',
    purchases: 'ግዢዎች',
    suppliers: 'አቅራቢዎች',
    stockIn: 'ክምችት ግባ',
    stockOut: 'ክምችት ውጣ',
    reorderLevel: 'የድጋሚ ትዕዛዝ ደረጃ',
    unitCost: 'የአንድ ክፍል ዋጋ',
    quantity: 'ብዛት',
    price: 'ዋጋ',
    date: 'ቀን',
    time: 'ሰዓት',
    cashier: 'ካሽሪ',
    manager: 'ማኔጀር',
    owner: 'ባለቤት',
    online: 'በመስመር ላይ',
    offline: 'ከመስመር ውጭ',
    syncing: 'በማመሳሰል ላይ...',
    language: 'ቋንቋ',
    theme: 'ገጽታ',
    darkMode: 'ጨለማ ሁነታ',
    lightMode: 'ብርሃን ሁነታ',
    logout: 'ውጣ',
    noItems: 'ምንም የለም',
    addItem: 'አክል',
    removeItem: 'አስወግድ',
    tapToPay: 'ክፈል',
    change: 'መለወጫ',
    items: 'እቃዎች',
    category: 'ምድብ',
    allCategories: 'ሁሉም',
    vat: 'ቫት',
    notes: 'ማስታወሻ',
    expenses: 'ወጪዎች',
    totalSales: 'ጠቅላላ ሽያጭ',
    openingBalance: 'የመክፈቻ ሂሳብ',
    closingBalance: 'የመዝጊያ ሂሳብ',
    cashInDrawer: 'በመሳቢያ ውስጥ ያለ ገንዘብ',
    difference: 'ልዩነት',
    lowStockItems: 'ዝቅተኛ ክምችት ያላቸው',
    completedBy: 'ያጠናቀቀው',
    printSummary: 'ማጠቃለያ አትም',
    closeRegister: 'መዝገብ ዝጋ',
    ethiopianDate: 'የኢትዮጵያ ቀን',
    gregorianDate: 'የጎርጎሪያን ቀን',
    menuItem: 'ምናሌ እቃ',
    saleComplete: 'ሽያጭ ተጠናቋል!',
    processing: 'በማስኬድ ላይ...',
    noSalesToday: 'ዛሬ ምንም ሽያጭ የለም',
    paymentMethod: 'የክፍያ ዘዴ',
    itemName: 'የእቃ ስም',
    unitPrice: 'የአንድ ዋጋ',
    lineTotal: 'ድምር',
    customerName: 'የደንበኛ ስም',
    phone: 'ስልክ',
    enterTransactionId: 'የግብይት መለያ ያስገቡ',
    cashPayment: 'ጥሬ ገንዘብ',
    digitalPayment: 'ዲጂታል ክፍያ',
    creditPayment: 'ብድር (ዎሎ)',
    eventCatering: 'ዝግጅት',
    etb: 'ብር',
  },
};

export const STORAGE_KEYS = {
  sales: 'habesha_pos_sales',
  customers: 'habesha_pos_customers',
  customerLedger: 'habesha_pos_customer_ledger',
  ingredients: 'habesha_pos_ingredients',
  stockMovements: 'habesha_pos_stock_movements',
  purchases: 'habesha_pos_purchases',
  dailyClosings: 'habesha_pos_daily_closings',
  currentUser: 'habesha_pos_current_user',
  pendingSales: 'habesha_pos_pending_sales',
  expenses: 'habesha_pos_expenses',
};